<?
/*
  Custom Fields
**/

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_59522aa739ff4',
	'title' => 'Article Display',
	'fields' => array (
		array (
			'key' => 'field_59522acef1c08',
			'label' => 'Articles to Show',
			'name' => 'show_articles',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				1 => '1',
				2 => '2',
				3 => '3',
				4 => '4',
				5 => '5',
			),
			'default_value' => array (
				0 => 3,
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5953cd2d7daa8',
	'title' => 'Banner Settings',
	'fields' => array (
		array (
			'key' => 'field_5953cd353ce0e',
			'label' => 'Banner Slides',
			'name' => 'banner_settings',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Add Slide',
			'sub_fields' => array (
				array (
					'key' => 'field_5971d5cff70ea',
					'label' => 'Slide Type',
					'name' => 'banner_slide_type',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'left' => 'Left Aligned',
						'center' => 'Center Aligned',
					),
					'default_value' => array (
						0 => 'Center Aligned',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_5953cdf73ce0f',
					'label' => 'Banner Text',
					'name' => 'banner_text',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
				array (
					'key' => 'field_5953ce493ce11',
					'label' => 'Banner Link Text',
					'name' => 'banner_link_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5953ce563ce12',
					'label' => 'Banner Link',
					'name' => 'banner_link',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5953ce6e3ce13',
					'label' => 'Banner Image',
					'name' => 'banner_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array (
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'page-templates/pr.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59d20a422a1fd',
	'title' => 'Career Fields',
	'fields' => array (
		array (
			'key' => 'field_59d20a5c60fdf',
			'label' => 'Job Link',
			'name' => 'job_link',
			'type' => 'url',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'careers',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_595b4c6a35ad3',
	'title' => 'Color Selector',
	'fields' => array (
		array (
			'key' => 'field_595b4c71a9916',
			'label' => 'Color Selector',
			'name' => 'color_selector',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'gd_block',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'gd_single_line',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'gd_link',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_597702e209583',
	'title' => 'Disclaimer',
	'fields' => array (
		array (
			'key' => 'field_597702e75dde1',
			'label' => 'Add Disclaimer',
			'name' => 'page_disclaimer',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_595a57ea2f06b',
	'title' => 'Fact Sheet Fields',
	'fields' => array (
		array (
			'key' => 'field_595a57f11441a',
			'label' => 'SEDOL',
			'name' => 'fact_sheet_sedol',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'fact_sheet',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_596cc4e0c0cde',
	'title' => 'Fact Sheets',
	'fields' => array (
		array (
			'key' => 'field_596cc84fbbc0d',
			'label' => 'Fact Sheet',
			'name' => 'fact_sheet_list',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 3,
			'layout' => 'table',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_596cc85ebbc0e',
					'label' => 'Fact Sheet',
					'name' => 'fact_sheet_select',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'fact_sheet',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
				array (
					'key' => 'field_596cc8a2bbc0f',
					'label' => 'Title',
					'name' => 'fact_sheet_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_596ccb5084a85',
					'label' => 'Text',
					'name' => 'fact_sheet_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_596f3b168198d',
	'title' => 'Page Setup',
	'fields' => array (
		array (
			'key' => 'field_596f3b1faa119',
			'label' => 'Page Theme',
			'name' => 'page_theme',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'blue' => 'Blue',
				'purple' => 'Purple',
			),
			'default_value' => array (
				0 => 'blue',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/products.php',
			),
		),
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'default',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59ce0c60e3ce2',
	'title' => 'Press Release Fields',
	'fields' => array (
		array (
			'key' => 'field_59ce0ce55be9d',
			'label' => 'Contact Block Title',
			'name' => 'contact_block_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59ce0d025be9e',
			'label' => 'Contact Block Row',
			'name' => 'contact_block_row',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_59ce138d9827d',
					'label' => 'Bold Left Column',
					'name' => 'bold_left',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
				),
				array (
					'key' => 'field_59ce0e205bea0',
					'label' => 'Left Column',
					'name' => 'left_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59ce0e395bea1',
					'label' => 'Right Column',
					'name' => 'right_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'press_release',
			),
		),
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/pr.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => 'Set fields on Press Releases page to set defaults that will appear on all articles. Set these fields on individual articles to override defaults',
));

acf_add_local_field_group(array (
	'key' => 'group_59ba7813e1a25',
	'title' => 'Video',
	'fields' => array (
		array (
			'key' => 'field_59ba782f1492c',
			'label' => 'Preview Image',
			'name' => 'preview_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_59ba784e1492d',
			'label' => 'Preview Text',
			'name' => 'preview_text',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
		array (
			'key' => 'field_59ba78601492e',
			'label' => 'Video',
			'name' => 'video_link',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/careers.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_595f482defc16',
	'title' => 'About Us Rows',
	'fields' => array (
		array (
			'key' => 'field_595f48ae4cf6c',
			'label' => 'About Row',
			'name' => 'about_row',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_595f48d44cf6d',
					'label' => 'Text',
					'name' => 'about_text',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
				array (
					'key' => 'field_595f48ec4cf6e',
					'label' => 'Fact Text',
					'name' => 'about_fact',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
				array (
					'key' => 'field_595f49224cf6f',
					'label' => 'Image',
					'name' => 'about_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_595f495d4cf71',
					'label' => 'Colour Theme',
					'name' => 'about_theme',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => 'fl_row_bg_color',
						'id' => '',
					),
					'choices' => array (
						't-about--white' => 'White',
						't-about--c' => 'Theme Color C',
						't-about--f' => 'Theme Color F',
						't-about--g' => 'Theme Color G',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/about.php',
			),
		),
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/who-we-are.php',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'excerpt',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_595cf3fc70cf9',
	'title' => 'Lower Product Banner',
	'fields' => array (
		array (
			'key' => 'field_595cf41585779',
			'label' => 'Lower Banner Slides',
			'name' => 'product_banner_slides',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_595f81192742c',
					'label' => 'Title',
					'name' => 'product_banner_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_595f9637c5210',
					'label' => 'Subtitle',
					'name' => 'product_banner_subtitle',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_595cf4408577a',
					'label' => 'Banner Text',
					'name' => 'product_banner_text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => 'wpautop',
				),
				array (
					'key' => 'field_595cf4768577d',
					'label' => 'Banner Image',
					'name' => 'product_banner_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/products.php',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'excerpt',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_595377a798139',
	'title' => 'Product/Page Information',
	'fields' => array (
		array (
			'key' => 'field_595377d07ac72',
			'label' => 'Rows',
			'name' => 'product_row',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_595378257ac73',
					'label' => 'Row Type',
					'name' => 'row_type',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'heavy' => 'Text Block',
						'two-column' => 'Two Column',
						'download' => 'Download',
						'image-txt' => 'Image, Text, & Link',
						'grid' => 'Grid',
						'list' => 'List',
						'list-two-column' => 'Two-Column List',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_59537ac77ac74',
					'label' => 'Title',
					'name' => 'row_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'two-column',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'image-txt',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'download',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59537b997ac77',
					'label' => 'Text',
					'name' => 'row_text',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'heavy',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'image-txt',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'heavy',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'grid',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'list',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'list-two-column',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
				array (
					'key' => 'field_59537c1d7ac7a',
					'label' => 'Row Background',
					'name' => 'row_bg',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'heavy',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'grid',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'list',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'list-two-column',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => 'fl_row_bg_color',
						'id' => '',
					),
					'choices' => array (
						'background--white' => 'White',
						'background--grey' => 'Grey',
						'background--a' => 'Theme Color A',
						'background--b' => 'Theme Color B',
						'background--c' => 'Theme Color C',
						'background--d' => 'Theme Color D',
						'background--e' => 'Theme Color E',
						'background--f' => 'Theme Color F',
						'background--g' => 'Theme Color G',
						'background--h' => 'Theme Color H',
						'background--i' => 'Theme Color I',
						'background--j' => 'Theme Color J',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
				),
				array (
					'key' => 'field_595cabfe50a45',
					'label' => 'Row Width',
					'name' => 'row_width',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'heavy',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'grid',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'list',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'normal' => 'Normal',
						'narrow' => 'Narrow',
					),
					'default_value' => array (
						0 => 'normal',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_59537d1e7ac7b',
					'label' => 'Left Column Text',
					'name' => 'row_text_left',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'two-column',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
				array (
					'key' => 'field_59537d447ac7d',
					'label' => 'Right Column Text',
					'name' => 'row_text_right',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'two-column',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
				array (
					'key' => 'field_59537f3c020f1',
					'label' => 'Row Image',
					'name' => 'row_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'image-txt',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'download',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_595a068425c0c',
					'label' => 'Show Link Button',
					'name' => 'row_show_button',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
				),
				array (
					'key' => 'field_59537e8a020f0',
					'label' => 'Download Link',
					'name' => 'row_download',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'download',
							),
							array (
								'field' => 'field_595a068425c0c',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_59537e25020ee',
					'label' => 'Link Destination',
					'name' => 'row_link',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'heavy',
							),
							array (
								'field' => 'field_595a068425c0c',
								'operator' => '==',
								'value' => '1',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'two-column',
							),
							array (
								'field' => 'field_595a068425c0c',
								'operator' => '==',
								'value' => '1',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'image-txt',
							),
							array (
								'field' => 'field_595a068425c0c',
								'operator' => '==',
								'value' => '1',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'grid',
							),
							array (
								'field' => 'field_595a068425c0c',
								'operator' => '==',
								'value' => '1',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'list',
							),
							array (
								'field' => 'field_595a068425c0c',
								'operator' => '==',
								'value' => '1',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'list-two-column',
							),
							array (
								'field' => 'field_595a068425c0c',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array (
					'key' => 'field_59537fc8020f3',
					'label' => 'Link Text',
					'name' => 'row_link_text_1',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'heavy',
							),
							array (
								'field' => 'field_595a068425c0c',
								'operator' => '==',
								'value' => '1',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'two-column',
							),
							array (
								'field' => 'field_595a068425c0c',
								'operator' => '==',
								'value' => '1',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'image-txt',
							),
							array (
								'field' => 'field_595a068425c0c',
								'operator' => '==',
								'value' => '1',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'grid',
							),
							array (
								'field' => 'field_595a068425c0c',
								'operator' => '==',
								'value' => '1',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'list',
							),
							array (
								'field' => 'field_595a068425c0c',
								'operator' => '==',
								'value' => '1',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'list-two-column',
							),
							array (
								'field' => 'field_595a068425c0c',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_595cfcca475cb',
					'label' => 'List Item',
					'name' => 'row_list_item',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'grid',
							),
						),
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'list',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => '',
					'max' => '',
					'layout' => 'table',
					'button_label' => 'Add Row',
					'sub_fields' => array (
						array (
							'key' => 'field_595cfdb8475cc',
							'label' => 'List Marker',
							'name' => 'list_marker',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'check' => 'Check',
								'custom_icon' => 'Custom Icon',
								'font_awesome' => 'Font Awesome',
							),
							'default_value' => array (
								0 => 'check',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array (
							'key' => 'field_595d0105475cd',
							'label' => 'Custom Icon',
							'name' => 'list_custom_icon',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_595cfdb8475cc',
										'operator' => '==',
										'value' => 'custom_icon',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_595d0123475ce',
							'label' => 'List Text',
							'name' => 'list_text',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_5970bc01193ce',
							'label' => 'Font Awesome Icon',
							'name' => 'list_font_awesome',
							'type' => 'text',
							'instructions' => 'Insert Icon name from font awesome list (example: fa-camera-retro). Full list can be found at http://fontawesome.io/icons/',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_595cfdb8475cc',
										'operator' => '==',
										'value' => 'font_awesome',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
				array (
					'key' => 'field_5970d77e5d7a0',
					'label' => 'Two-Column List Item',
					'name' => 'row_list_item_two',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_595378257ac73',
								'operator' => '==',
								'value' => 'list-two-column',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => '',
					'max' => '',
					'layout' => 'table',
					'button_label' => 'Add Row',
					'sub_fields' => array (
						array (
							'key' => 'field_5970d7ca5d7a1',
							'label' => 'Left Text',
							'name' => 'list_left',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_5970d7e25d7a2',
							'label' => 'Right Text',
							'name' => 'list_right',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
					),
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/products.php',
			),
		),
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'default',
			),
		),
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/library.php',
			),
		),
	),
	'menu_order' => 20,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'excerpt',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_595cee5a398a6',
	'title' => 'Product CTA',
	'fields' => array (
		array (
			'key' => 'field_595cee6748442',
			'label' => 'Left Column',
			'name' => 'cta_text_left',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
		array (
			'key' => 'field_595ceed048443',
			'label' => 'Right Column',
			'name' => 'cta_text_right',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/products.php',
			),
		),
	),
	'menu_order' => 30,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'excerpt',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_595e38d4e529b',
	'title' => 'Product Case Study',
	'fields' => array (
		array (
			'key' => 'field_595e396e111b5',
			'label' => 'Title',
			'name' => 'case_study_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_595e39b3111b7',
			'label' => 'Left Column',
			'name' => 'case_study_text_left',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
		array (
			'key' => 'field_595e39d8111b8',
			'label' => 'Right Column',
			'name' => 'case_study_text_right',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
		array (
			'key' => 'field_595e39a2111b6',
			'label' => 'Show Button',
			'name' => 'case_study_show_button',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_595e39e6111b9',
			'label' => 'Link',
			'name' => 'case_study_link',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_595e39a2111b6',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_595e39ef111ba',
			'label' => 'Link Text',
			'name' => 'case_study_link_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_595e39a2111b6',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/products.php',
			),
		),
	),
	'menu_order' => 40,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59ba79d3df424',
	'title' => 'Benefits',
	'fields' => array (
		array (
			'key' => 'field_59ba79d40026a',
			'label' => 'Summary Points',
			'name' => 'summary_points',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Summary Point',
			'sub_fields' => array (
				array (
					'key' => 'field_59ba79d4026c6',
					'label' => 'Icon',
					'name' => 'summary_icon',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_59ba79d4026d6',
					'label' => 'Font Awesome Icon',
					'name' => 'summary_fa_icon',
					'type' => 'text',
					'instructions' => 'Insert Icon name from font awesome list (example: fa-camera-retro). Full list can be found at http://fontawesome.io/icons/. Note: Font Icon image will override any Font Awesome Icons',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59ba79d4026e2',
					'label' => 'Summary Title',
					'name' => 'summary_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59ba79d4026ed',
					'label' => 'Summary Text',
					'name' => 'summary_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/careers.php',
			),
		),
	),
	'menu_order' => 50,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_595f8155df275',
	'title' => 'Product Summary',
	'fields' => array (
		array (
			'key' => 'field_595f8168c7c35',
			'label' => 'Summary Points',
			'name' => 'summary_points',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => 4,
			'layout' => 'table',
			'button_label' => 'Add Summary Point',
			'sub_fields' => array (
				array (
					'key' => 'field_595f81f9c7c36',
					'label' => 'Icon',
					'name' => 'summary_icon',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_5971d9c286519',
					'label' => 'Font Awesome Icon',
					'name' => 'summary_fa_icon',
					'type' => 'text',
					'instructions' => 'Insert Icon name from font awesome list (example: fa-camera-retro). Full list can be found at http://fontawesome.io/icons/. Note: Font Icon image will override any Font Awesome Icons',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_595f8211c7c37',
					'label' => 'Summary Title',
					'name' => 'summary_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_595f8227c7c38',
					'label' => 'Summary Text',
					'name' => 'summary_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/products.php',
			),
		),
	),
	'menu_order' => 50,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
